# syntax=docker/dockerfile:1
FROM rabbitmq:latest
RUN apt-get update 
RUN apt-get install -y git 
RUN apt-get install -y python3 
RUN apt-get install -y python3-pip
RUN apt-get install -y net-tools
RUN apt-get install -y openssh-client
RUN apt-get install -y vim
RUN apt-get install -y iputils-ping
RUN pip3 install flask pika uuid requests Flask-JSGlue flask_cors pydantic bson pymongo flask_restful
RUN git clone https://github.com/ntdai95/AuctionWebsite.git
