FROM ubuntu:latest
RUN apt-get update 
RUN apt-get install -y git 
RUN apt-get install -y python3 
RUN apt-get install -y python3-pip
RUN apt-get install -y net-tools
RUN apt-get install -y vim
RUN apt-get install -y iputils-ping
RUN pip3 install Jinja2>=2.10.1,<3.1 Flask pika PyMySQL uuid requests Flask-JSGlue Flask_Cors pydantic Flask_RESTful cryptography
RUN git clone https://github.com/ntdai95/AuctionWebsite.git
