FROM mongo:latest
RUN apt-get update 
RUN apt-get install -y git 
RUN apt-get install -y python3 
RUN apt-get install -y python3-pip
RUN apt-get install -y net-tools
RUN apt-get install -y vim
RUN apt-get install -y iputils-ping
RUN pip3 install Flask pika uuid requests Flask_Cors pydantic bson pymongo Flask_RESTful
RUN git clone https://github.com/ntdai95/AuctionWebsite.git
