FROM mongo:latest
RUN apt-get update 
RUN apt-get install -y git 
RUN apt-get install -y python3 
RUN apt-get install -y python3-pip
RUN apt-get install -y net-tools
RUN apt-get install -y vim
RUN apt-get install -y iputils-ping
RUN git clone https://github.com/ntdai95/AuctionWebsite.git
WORKDIR /AuctionWebsite/setup
RUN pip3 install -r requirements.txt
