FROM mysql:latest
RUN microdnf install -y git python3 python3-pip net-tools vim-minimal iputils
RUN git clone https://github.com/ntdai95/AuctionWebsite.git
WORKDIR /AuctionWebsite/setup
RUN pip3 install -r requirements.txt
