version: "3.9"
networks:
    netBackEnd:
     driver: bridge
     ipam:
       driver: default

services:
  itemsdb:
    build:
      context: ./
      dockerfile: Dockerfile_MySQL
    container_name: itemsdb
    networks:
      - netBackEnd
    volumes:
      - ./item:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: ${ITEMS_DB_PASSWORD}
      MYSQL_DATABASE: items
      MYSQL_USER: ${ITEMS_DB_USER}
      MYSQL_PASSWORD: ${ITEMS_DB_PASSWORD}
      MYSQL_TCP_PORT: 3317

  items:
    build:
      context: ./
      dockerfile: Dockerfile_App
    container_name: items
    networks:
      - netBackEnd
    ports:
      - 3307:3307
    links:
      - itemsdb
    working_dir: /AuctionWebsite/items/
    command: "flask run"
    environment:
      FLASK_APP : restful_items.py
      FLASK_RUN_PORT: 3307
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_ENV: development
      WORKING_DIRECTORY: /AuctionWebsite/items/
      ITEMS_DB_USER: ${ITEMS_DB_USER}
      ITEMS_DB_PASSWORD: ${ITEMS_DB_PASSWORD}

  usersdb:
    build:
      context: ./
      dockerfile: Dockerfile_MySQL
    container_name: usersdb
    networks:
      - netBackEnd
    volumes:
      - ./user:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: ${USERS_DB_PASSWORD}
      MYSQL_DATABASE: user
      MYSQL_USER: ${USERS_DB_USER}
      MYSQL_PASSWORD: ${USERS_DB_PASSWORD}
      MYSQL_TCP_PORT: 3322

  users:
    build:
      context: ./
      dockerfile: Dockerfile_App
    container_name: users
    networks:
      - netBackEnd
    ports:
      - 3312:3312
    links:
      - usersdb
    working_dir: /AuctionWebsite/user/
    command: "flask run"
    environment:
      FLASK_APP : app.py
      FLASK_RUN_PORT: 3312
      FLASK_RUN_HOST: 0.0.0.0
      WORKING_DIRECTORY: /AuctionWebsite/user/
      USERS_DB_USER: ${USERS_DB_USER}
      USERS_DB_PASSWORD: ${USERS_DB_PASSWORD}

  auctionsdb:
    build:
      context: ./
      dockerfile: Dockerfile_MySQL
    container_name: auctionsdb
    networks:
      - netBackEnd
    volumes:
      - ./auction:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: ${AUCTIONS_DB_PASSWORD}
      MYSQL_DATABASE: auctions
      MYSQL_USER: ${AUCTIONS_DB_USER}
      MYSQL_PASSWORD: ${AUCTIONS_DB_PASSWORD}
      MYSQL_TCP_PORT: 3328

  auctions:
    build:
      context: ./
      dockerfile: Dockerfile_App
    container_name: auctions
    networks:
      - netBackEnd
    ports:
      - 3318:3318
    links:
      - auctionsdb
    working_dir: /AuctionWebsite/auctions/
    command: "flask run"
    environment:
      FLASK_APP : restful_auctions.py
      FLASK_RUN_PORT: 3318
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_ENV: development
      WORKING_DIRECTORY: /AuctionWebsite/auctions/
      AUCTIONS_DB_USER: ${AUCTIONS_DB_USER}
      AUCTIONS_DB_PASSWORD: ${AUCTIONS_DB_PASSWORD}

  transactionsdb:
    build:
      context: ./
      dockerfile: Dockerfile_MySQL
    container_name: transactionsdb
    networks:
      - netBackEnd
    volumes:
      - ./transaction:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: ${TRANSACTIONS_DB_PASSWORD}
      MYSQL_DATABASE: transaction
      MYSQL_USER: ${TRANSACTIONS_DB_USER}
      MYSQL_PASSWORD: ${TRANSACTIONS_DB_PASSWORD}
      MYSQL_TCP_PORT: 3315

  transactions:
    build:
      context: ./
      dockerfile: Dockerfile_App
    container_name: transaction
    networks:
      - netBackEnd
    ports:
      - 3305:3305
    links:
      - transactionsdb
    working_dir: /AuctionWebsite/transactions/
    command: "flask run"
    environment:
      FLASK_APP : restful_transaction.py
      FLASK_RUN_PORT: 3305
      FLASK_RUN_HOST: 0.0.0.0
      WORKING_DIRECTORY: /AuctionWebsite/transactions/
      TRANSACTIONS_DB_USER: ${TRANSACTIONS_DB_USER}
      TRANSACTIONS_DB_PASSWORD: ${TRANSACTIONS_DB_PASSWORD}

  watchlistdb:
    build:
      context: ./
      dockerfile: Dockerfile_MySQL
    container_name: watchlistdb
    networks:
      - netBackEnd
    volumes:
      - ./watchlist:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: ${WATCHLIST_DB_PASSWORD}
      MYSQL_DATABASE: watchlist
      MYSQL_USER: ${WATCHLIST_DB_USER}
      MYSQL_PASSWORD: ${WATCHLIST_DB_PASSWORD}
      MYSQL_TCP_PORT: 3321

  watchlist:
    build:
      context: ./
      dockerfile: Dockerfile_App
    container_name: watchlist
    networks:
      - netBackEnd
    ports:
      - 3311:3311
    links:
      - watchlistdb
    working_dir: /AuctionWebsite/watchlist/
    command: "flask run"
    environment:
      FLASK_APP : restful_watchlist.py
      FLASK_RUN_PORT: 3311
      FLASK_RUN_HOST: 0.0.0.0
      WORKING_DIRECTORY: /AuctionWebsite/watchlist/
      WATCHLIST_DB_USER: ${WATCHLIST_DB_USER}
      WATCHLIST_DB_PASSWORD: ${WATCHLIST_DB_PASSWORD}

  frontend:
    build:
      context: ./
      dockerfile: Dockerfile_App
    container_name: frontend
    networks:
      - netBackEnd
    ports:
      - 3309:3309
    working_dir: /AuctionWebsite/frontend/
    command: "flask run"
    environment:
      FLASK_APP : index.py
      FLASK_RUN_PORT: 3309
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_ENV: development
      WORKING_DIRECTORY: /AuctionWebsite/frontend/

  messagesmongo:
    build:
      context: ./
      dockerfile: Dockerfile_Mongo
    container_name: messagesmongo
    networks:
      - netBackEnd
    ports:
      - 3313:3313
    command: ["--bind_ip_all"]
    working_dir: /AuctionWebsite/messages/
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MESSAGES_MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MESSAGES_MONGO_PASSWORD}
      WORKING_DIRECTORY: /AuctionWebsite/messages/

  messagesrabbitmq:
    build:
      context: ./
      dockerfile: Dockerfile_RabbitMQ
    container_name: messagesrabbitmq
    networks:
      - netBackEnd
    ports:
      - 3314:3314
    working_dir: /AuctionWebsite/messages/
    environment:
      WORKING_DIRECTORY: /AuctionWebsite/messages/

  messages:
    build:
      context: ./
      dockerfile: Dockerfile_App
    container_name: messages
    networks:
      - netBackEnd
    links:
      - messagesrabbitmq
      - messagesmongo
    working_dir: /AuctionWebsite/messages/
    command: "python3 message_rpc_server.py"
    environment:
      WORKING_DIRECTORY: /AuctionWebsite/messages/
      MESSAGES_MONGO_USER: ${MESSAGES_MONGO_USER}
      MESSAGES_MONGO_PASSWORD: ${MESSAGES_MONGO_PASSWORD}
      EMAIL_ADDRESS: ${EMAIL_ADDRESS}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
